name: bmicalc
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flip_card: ^0.7.0
  syncfusion_flutter_gauges: ^25.1.42
  animated_text_kit: ^4.2.2
  pdf: ^3.10.8
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  gallery_saver: ^2.3.2
  flutter_animation_progress_bar: ^2.3.1
  shake_animation_widget: ^3.0.4
  fancy_containers: ^0.0.5
  screenshot: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
